version: '2'
services:
  flask:
    build: ./flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./flaskapp:/code
    depends_on:
      - dynamodb
    restart: always
  dynamodb:
    build: ./dynamodb
